// ============================================================================
// 🚫 LISTA NEGRA DE PDFs (Imagens e Arquivos sem data)
// Cole aqui dentro do array as URLs que o terminal exibir no final da raspagem.
// ============================================================================

export const PDFs_IGNORADOS: string[] =
  [
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=7nj433ffr06o8s2mmv7uedaext666um1",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=4d4f8rl7fuuozs8gjnsrf5lko1h6lfin",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=gn3z3g5freukszg2aus256yhafqui037",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=oxj1ngs7vf56mwpdhzg7otwz41d0qkj4",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=u01vl45u131tzqo79y42gtd35dyv7u1c",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=q8oetwrkedkahrocoxktmuw90te78r63",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=q9qvr1xwkmjnu7qbf379l5whl2s6h813",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=8qxzccigsc6i71tk4qj448kkgspmo7d7",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=z8mozzv3wohqpp671u7b6jf8pkvc3owg",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=yx1drjt4hjkl3a8c9stq7j416j93djj8",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=hlerueubrxyia24yx8amaey8vjshregw",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=jns6u8y1woogo5rwjea672e9fp1b1otc",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=gampw6ehwm9mbrpvics3ob3aefwwjnb6",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=2085lxg0s82jrvgihrczgexsiiyvg89b",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=lst1q7urjs5fs6mlflvc420iflxv0ie3",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=brkidqqefywtp2ourp8f67gpfirmnrsu",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=9qfizwopt1hedv5am1zl6vmth6vyltaz",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=cr8wt382bertxr1w0onofhfweekfaqtp",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=pqvid7kbhwu43kw4p4a1l768eawezd1m",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=n2jr7e7509s4f9r1s1ml4o45wg5lqr8i",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=8lw1lzo304innarredk9j9zeds1k9eqi",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=s3fu5jf0t9y0kkvxs12g2r4evxvcc3d1",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=w4z32wcw8qwj4w27j3t8jit5910b3s4j",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=mznpjwwhc12tar4zb1l9d8hlhxawwhse",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=8adraut6b7urulplmpn9q23prckc984v",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=0u0ivzzm8tvsinhu3ks3l6r4gntgwxrs",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=f8oauzdevrvivrju9mqvexazswen4jfn",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=lqq3rsj6j7sit44t5yl4309x24kpzp5t",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=vt81r8j39gfq7ljtrb2ffa2vbprh5768",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=gm6qrfzwu5sj9jxzdopr8ndl5dgsf8t6",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=01sg2nnlhu81pglx763tm2qsk5zlub7a",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=mrgp6igc7qsxvi0fx5seyi6e7cr01ain",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=cflwggoq6hug1yxe2xv0byxooojso4wr",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=43ixx742s4kf58t574adykvrco0m69s4",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=00cogn7wfbxjnt4266thc3m974ohz0h0",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=2680060a44etpfw0p4au16gdjc5isihd",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=wrz42txx2y3qifstcu4kt0tvp5t17nan",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=lwc2n1lkwek6jwn4k1ues10oa7qf4z8f",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=fvtmifqi08fdmlv566airvww5rpcxklp",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=utxigbdfcawj38r5xib2yr447m3a8iov",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=1ynaan6toz6ohzq8ma51fqk47bkn4x9f",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=0lssi0niqztaisewslgovmui2scjl8iz",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=eauqozrwgut74h3elsexqc41w44bi7ad",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=29y8fji2igvpf7fji2tax97i7i2decna",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=uhtx1s8zd9tv56u640cejstxkvnqv3qr",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=njc0mtog4efz42nlh497w2bbcf898y2m",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=vynn9nyse4wfiqeruh0ihd65cm4afdfj",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=p3dnsg2se1by9t754tp8sv0zzipye29t",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=i6uhg28hdn86db0a7vfclkflycl19vxn",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=334m7y6iumec1k9718uvmnpvjq88ofkq",
    "https://sjduaspontes.sp.gov.br/DownloadServlet?id=slqmjp7gekv0zbuwspwq0mnlx7u2y34n"
  ];